try {
  /* code */
  /*exception creation*/
  throw "user not found"
} catch (err) {
  console.log(err);
}finally{
  /*any way*/
}